name: Compress Existing Images
on:
  workflow_dispatch:

jobs:
  compress-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Compress Images
        uses: calibreapp/image-actions@1.1.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: '80'
          pngQuality: '80'
          webpQuality: '80'
          compressOnly: 'blog/test/**'  # 添加这行，只处理测试文件夹
          ignorePaths: 'node_modules/**,dist/**'
